WIP - Removal of the scroll function
lnls-sirius/archiver-viewer pull request #66
Opened 2022-04-05 17:31 UTC by RafaelLyra8

Removal of the variables of the scroll function

2022-04-05 18:48 UTC, anacso17 approved these changes

2022-04-09 00:59 UTC, xresende approved these changes

2022-04-09 01:02 UTC, xresende commented
@RafaelLyra8 , github is indicating conflict between this branch and master branch

2022-04-09 01:03 UTC, xresende requested changes
conflict between PR commits and master

2022-04-11 11:17 UTC, xresende approved these changes

2022-04-11 11:55 UTC, merged